/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author pierr
 */
public class CustomerHomePage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerHomePage
     */
    public CustomerHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Automatic = new javax.swing.JRadioButton();
        Electric = new javax.swing.JRadioButton();
        Luxury = new javax.swing.JRadioButton();
        Utilitary = new javax.swing.JRadioButton();
        Manual = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jDateChooser6 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Automatic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Automatic.setForeground(new java.awt.Color(255, 255, 255));
        Automatic.setText("Automatic");
        Automatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutomaticActionPerformed(evt);
            }
        });
        jPanel1.add(Automatic);
        Automatic.setBounds(420, 270, 110, 30);

        Electric.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Electric.setForeground(new java.awt.Color(255, 255, 255));
        Electric.setText("Electric");
        Electric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectricActionPerformed(evt);
            }
        });
        jPanel1.add(Electric);
        Electric.setBounds(420, 330, 90, 31);

        Luxury.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Luxury.setForeground(new java.awt.Color(255, 255, 255));
        Luxury.setText("Luxury");
        Luxury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuxuryActionPerformed(evt);
            }
        });
        jPanel1.add(Luxury);
        Luxury.setBounds(530, 330, 100, 30);

        Utilitary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Utilitary.setForeground(new java.awt.Color(255, 255, 255));
        Utilitary.setText("Utilitary");
        Utilitary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilitaryActionPerformed(evt);
            }
        });
        jPanel1.add(Utilitary);
        Utilitary.setBounds(650, 330, 100, 30);

        Manual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Manual.setForeground(new java.awt.Color(255, 255, 255));
        Manual.setText("Manual");
        Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualActionPerformed(evt);
            }
        });
        jPanel1.add(Manual);
        Manual.setBounds(650, 270, 100, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("GPS");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(420, 440, 70, 40);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Air Conditioner");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(420, 390, 150, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 250, 360);

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/image/search_database_32px.png"))); // NOI18N
        jButton2.setText("Search for the perfect car");
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 570, 510, 50);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(870, 210, 270, 350);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel8.setText("Rent a car when and where do you want it !");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 0, 750, 50);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("What kind of car do you want ?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 200, 380, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Return Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 110, 160, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Departure Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 110, 150, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Popular cars of the moment ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 160, 270, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Your recent historic ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 160, 210, 50);

        jDateChooser3.setDateFormatString("dd MMM yyyy");
        jPanel1.add(jDateChooser3);
        jDateChooser3.setBounds(430, 110, 130, 30);
        jPanel1.add(jDateChooser4);
        jDateChooser4.setBounds(710, 110, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/image/Fond.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 630);
        jPanel1.add(jDateChooser5);
        jDateChooser5.setBounds(440, 110, 96, 22);
        jPanel1.add(jDateChooser6);
        jDateChooser6.setBounds(710, 120, 96, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed
        // TODO add your handling code here:
        if(Manual.isSelected()){
            Automatic.setSelected(false);
            
        }
    }//GEN-LAST:event_ManualActionPerformed

    private void AutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutomaticActionPerformed
        // TODO add your handling code here:
        if(Automatic.isSelected()){
            Manual.setSelected(false);
        }
    }//GEN-LAST:event_AutomaticActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void ElectricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectricActionPerformed
        // TODO add your handling code here:
        if(Electric.isSelected()){
            Utilitary.setSelected(false);
            Luxury.setSelected(false);
        }
    }//GEN-LAST:event_ElectricActionPerformed

    private void LuxuryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuxuryActionPerformed
        // TODO add your handling code here:
        if(Luxury.isSelected()){
            Utilitary.setSelected(false);
            Electric.setSelected(false);
        }
    }//GEN-LAST:event_LuxuryActionPerformed

    private void UtilitaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilitaryActionPerformed
        // TODO add your handling code here:
        if(Utilitary.isSelected()){
            Luxury.setSelected(false);
            Electric.setSelected(false);
        }
    }//GEN-LAST:event_UtilitaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Automatic;
    private javax.swing.JRadioButton Electric;
    private javax.swing.JRadioButton Luxury;
    private javax.swing.JRadioButton Manual;
    private javax.swing.JRadioButton Utilitary;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
